LLPP\MyTestBundle\Entity\Spedizioni:
    type: entity
    table: spedizioni
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tipo:
            type: string
            nullable: false
            length: 60
            fixed: false
            default: ''
        valore:
            type: integer
            nullable: false
            unsigned: false
            default: '0'
        costo:
            type: float
            nullable: false
            precision: 10
            scale: 0
    lifecycleCallbacks: {  }
